#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <stdarg.h>

void die(char* fmt, ...) {
  va_list ap;
  va_start(ap, fmt);

  vfprintf(stderr, fmt, ap);
  fprintf(stderr, "\n");
  exit(1);
}

char* read_source(char* fname) {
  FILE* file = fopen(fname, "r");
  if (!file) die("%s: %s", strerror(errno), fname);
  
  // get file size
  fseek(file, 0L, SEEK_END);
  int size = ftell(file);
  rewind(file);
  
  // allocate
  char* source = calloc(sizeof(char), size + 1);
  if (!source) die("Can't allocate buffer for %s", fname);
  
  // read
  int read = fread(source, 1, size, file);
  if (read < size) die("%s: %s", strerror(errno), fname);
  source[size] = '\0';

  return source;
}

int main(int argc, char** argv) {
  if (argc < 3 || argc > 4) {
    fprintf(stderr, "Usage: %s VARNAME TEXTFILE [CFILE]\n", argv[0]);
    return 1;
  }

  char* var_name = argv[1];
  char* source_name = argv[2];
  char* source = read_source(source_name);

  FILE* out = stdout;
  if (argc == 4) {
    char* fname = argv[3];
    out = fopen(fname, "w");
    if (!out) die("%s: %s", strerror(errno), fname);
  }
  
  char* p = source;
  char c;
  int col = 0;

  fprintf(out, "/* This file is generated by %s. DO NOT EDIT */\n\n", source_name);
  fprintf(out, "char %s[] = {", var_name);
  
  while((c = *p) != '\0') {
    if (col % 12 == 0) fprintf(out, "\n    ");
    p++;
    col++;
    fprintf(out, "0x%02x, ", c);
  }
  
  fprintf(out, "0"); // put terminating zero
  fprintf(out, "\n};\n");
  
  return 0;
}
